### ISSUE TITLE
can not init project

### ISSUE THREAD

**Issue by xdewx** [extension-js/extension.js#270]
`npx extension create browser-extension `

node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'svelte-preprocess'
Require stack:
- /home/xxx/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-develop/dist/module.js
- /home/xxx/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/xxx/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-develop/dist/module.js:76:14762)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xxx/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-develop/dist/module.js',
    '/home/xxx/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js'
  ]
}

Node.js v21.7.3

**Comment by cezaraugusto** [comment]
@xdewx thanks for reporting. what shows up when you run `npx extension --version`?

**Comment by cezaraugusto** [comment]
great! what about Extension.js?

```
npx extension --version
```

also, can you try running the latest release? 

```
npx extension@latest create browser-extension
```

**Comment by cezaraugusto** [comment]
should be fixed in latest `v2.0.0-rc.27`

**Comment by matejaputic** [comment]
I'm still seeing this issue, even with rc.27

```
$ npx extension create my-extension
Need to install the following packages:
extension@2.0.0-rc.27
Ok to proceed? (y)

🐣 - Starting a new browser extension named my-extension...
🤝 - Ensuring my-extension folder exists...
🤞 - Checking if destination path is writeable...
🔎 - Scanning for potential conflicting files...
🧰 - Installing my-extension...
Error: ENOENT: no such file or directory, open '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
    at async open (node:internal/fs/promises:634:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async overridePackageJson (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:329:32)
    at async extensionCreate (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:575:9)
    at async Command.<anonymous> (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
}
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: ENOENT: no such file or directory, open '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
    at async open (node:internal/fs/promises:634:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async overridePackageJson (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:329:32)
    at async extensionCreate (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:575:9)
    at async Command.<anonymous> (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
}

Node.js v23.11.0
```

It does create the following:
```
my-extension/
├── manifest.json
├── package.json
└── README.md
```

but I'm not sure if that's sufficient to ignore the error and move forward.

**Comment by tingkelvin** [comment]
> I'm still seeing this issue, even with rc.27
> 
> ```
> $ npx extension create my-extension
> Need to install the following packages:
> extension@2.0.0-rc.27
> Ok to proceed? (y)
> 
> 🐣 - Starting a new browser extension named my-extension...
> 🤝 - Ensuring my-extension folder exists...
> 🤞 - Checking if destination path is writeable...
> 🔎 - Scanning for potential conflicting files...
> 🧰 - Installing my-extension...
> Error: ENOENT: no such file or directory, open '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
>     at async open (node:internal/fs/promises:634:25)
>     at async Object.readFile (node:internal/fs/promises:1238:14)
>     at async overridePackageJson (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:329:32)
>     at async extensionCreate (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:575:9)
>     at async Command.<anonymous> (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js:95:5) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
> }
> node:internal/process/promises:394
>     triggerUncaughtException(err, true /* fromPromise */);
>     ^
> 
> Error: ENOENT: no such file or directory, open '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
>     at async open (node:internal/fs/promises:634:25)
>     at async Object.readFile (node:internal/fs/promises:1238:14)
>     at async overridePackageJson (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:329:32)
>     at async extensionCreate (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/dist/module.js:575:9)
>     at async Command.<anonymous> (/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension/dist/cli.js:95:5) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/Users/macos/.npm/_npx/3b1fc9cdc75022aa/node_modules/extension-create/template/package.json'
> }
> 
> Node.js v23.11.0
> ```
> 
> It does create the following:
> 
> ```
> my-extension/
> ├── manifest.json
> ├── package.json
> └── README.md
> ```
> 
> but I'm not sure if that's sufficient to ignore the error and move forward.

same happened to me

**Comment by tingkelvin** [comment]
> npx extension@latest create my-extension

running with node 22

**Comment by cezaraugusto** [comment]
@xdewx npx cache is huge, try explicitly running latest `extension@2.0.0-rc.36`. lmk how it goes

**Comment by anon-legion** [comment]
I don't think this issue has been fixed, `pnpx extension@latest create <your-extension-name>` throws this same error until now. Have tried use standard npm and bun with the same issue.
