### ISSUE TITLE
Can't load "content_scripts/content-0.js" ,Because it's not UTF-8 encoded

### ISSUE THREAD

**Issue by John-Chan** [extension-js/extension.js#94]
<img width="338" alt="image" src="https://github.com/cezaraugusto/extension.js/assets/2360910/43840ea3-179d-4d9a-a154-ebeabc5a9e13">

Create a project via :

```shell
 npx extension create my-extension --template=vue-typescript
```

and run `npm run start`

**Comment by cezaraugusto** [comment]
hi @John-Chan thanks for reporting.


Could you try running the React-TypeScript template to see if thee bug happens as well? I'm looking to know if the issue is template-specific.

```
npx extension create my-extension --template=vue-typescript
```

**Comment by John-Chan** [comment]
The React-TypeScript template cannot run due to icon path issues( #87), and it's uncertain whether there is an issue with UTF-8 encoding.

```
npx extension create my-extension-react --template=react-typescript
```

<img width="344" alt="image" src="https://github.com/cezaraugusto/extension.js/assets/2360910/d7b50b29-2c85-445d-bd96-d0e76d7ba8ae">

**Comment by OSpoon** [comment]
我猜测是 webpack@5.91.0  中的 output.cssHeadDataCompression 选项在 production 环境启用导致的 content-0.js 包含了一个无法识别的字符，我尝试关闭 output.cssHeadDataCompression 选项可以避免这个问题，我也在 webpack@5.92.0 中发现了一项变更，最新的版本将不会出现无法识别的字符。
https://github.com/webpack/webpack/blob/34e2561addb0f65a7a6fb0ce7ae1aea4cd1d599f/lib/css/CssLoadingRuntimeModule.js#L227

**Comment by cezaraugusto** [comment]
@OSpoon thanks for investigating! Did updating webpack solved the issue? I'm not able to reproduce

**Comment by OSpoon** [comment]
![5 91 0](https://github.com/cezaraugusto/extension.js/assets/10126623/548d48e3-b823-4f31-946c-2e6624fed8d2)

@cezaraugusto, I reproduced this issue using the code of the main branch. For this inssus, I tried two solutions:

1. To disable the `output.cssHeadDataCompression` option.
![cssHeadDataCompression false](https://github.com/cezaraugusto/extension.js/assets/10126623/61d4a95c-8ef0-4f17-b5b9-d5f9793a0cba)

3. Upgrade webpack to the latest version.
![5 92 0](https://github.com/cezaraugusto/extension.js/assets/10126623/93e434d3-1c01-4df1-8874-a5622d372a7d)

**Comment by cezaraugusto** [comment]
thanks @OSpoon, PR opened to bump webpack

**Comment by cezaraugusto** [comment]
@John-Chan could you please try again? I just released v1.8.0 which should fix it.

```
npx extension@1.8.0 start my-extension --template=vue-typescript
```

<img width="1476" alt="Screenshot 2024-06-19 at 16 41 26" src="https://github.com/extension-js/extension.js/assets/4672033/b49d96ab-6899-4670-a771-0fda717c587f">

Also please note that `start` will bundle your extension in production mode without live-reload support. For development you want to run the `dev` command.

Let me know if that works for you so we can close this one. Thanks!

**Comment by John-Chan** [comment]
Compared to before, vue templates no longer pop up utf8 encoding errors, but the project still can't start successfully because of the icon path problem. Maybe we need to wait for the icon path issue to be resolved and try again.

**Comment by cezaraugusto** [comment]
@John-Chan @OSpoon happy to share that this bug is finally fixed.

```
# Ensure you run @latest as npx cache system can trick you are not
npx extension@latest create my-extension --template=vue-typescript
```

If I'm wrong, let me know!

**Comment by John-Chan** [comment]
The ICON path issue still exists, manually copying the file to the `dist/chrome/icons` path works. So the utf8 encoding issue should be fixed.

<img width="904" alt="image" src="https://github.com/extension-js/extension.js/assets/2360910/51a74e50-567f-43b4-868f-d497dba2e97e">

**Comment by OSpoon** [comment]
hi @cezaraugusto, `webpack-run-edge-extension`, `webpack-run-chrome-extension` and `webpack-browser-extension-manifest` were last updated 12 days ago, Do you need to release the latest version?

**Comment by cezaraugusto** [comment]
@OSpoon just bumped all three versions but can't repro the bug yet. do you?

<img width="376" alt="Screenshot 2024-07-02 at 22 16 57" src="https://github.com/extension-js/extension.js/assets/4672033/148399e8-a821-4647-8526-3b9a87099a9c">

**Comment by OSpoon** [comment]
@cezaraugusto, I don't see the new version of `webpack-browser-extension-manifest`

**Comment by cezaraugusto** [comment]
Oops my bad, released now

<img width="422" alt="Screenshot 2024-07-03 at 08 40 41" src="https://github.com/extension-js/extension.js/assets/4672033/782d43f0-2a1e-4739-8c97-6f12101d3e1b">

**Comment by OSpoon** [comment]
@cezaraugusto Regarding the problem of the path in the `win` environment, I have verified it, and please @John-chan can try again in his free time, thank you very much ~

**Comment by John-Chan** [comment]
> @cezaraugusto Regarding the problem of the path in the `win` environment, I have verified it, and please @John-Chan can try again in his free time, thank you very much ~

Great! It's works

**Comment by cezaraugusto** [comment]
thanks for confirming @John-Chan! feel free to report anything else you find weird.

@OSpoon thanks for digging into it! 💯

Closing as fixed 🎉
